# Generated by Django 4.0.2 on 2022-02-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
